name: Build and publish a Hex package

on:
  push:
    tags:
      - v*

jobs:
  publish:

    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10'
        otp-version: '22'

    - name: Install Dependencies
      run: mix deps.get

    - name: Check code formatting
      run: mix format --check-formatted

    - name: Compile source
      run: mix compile

    - name: Compile source (prod)
      run: mix compile
      env:
        MIX_ENV: prod

    - name: Check code quality
      run: mix credo

    - name: Run Tests
      run: mix test

    - name: Build package
      run: mix hex.build
      env:
        MIX_ENV: prod

    - name: Publish package
      run: mix hex.publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
